Refactor session transaction on sqlite store
kedro-org/kedro-viz pull request #1358
Opened 2023-05-15 15:43 UTC by rashidakanchwala

## Description

This ticket is a small refactor on the way we do session transactions on sqlite store. Previously we used different ways for session transactions i.e.
-  on RunsRepository we used context manager 
- on sqlite_store.py we use a session generator get_db() which was a bit odd. 

I have changed the sqlite_store.py to use context manager now just like how it is done in the Runs Repository. 

Besides this we have made a small change to database.py to do create the table metadata in create_db_engine function. 

Thanks @antonymilne for highlighting this and helping figure out :) 

## Development notes

## QA notes

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

2023-05-15 16:57 UTC, antonymilne commented on package/kedro_viz/integrations/kedro/sqlite_store.py
> +        self._db_session = session_class
```suggestion
        self._db_session = create_db_engine(self.location)
```
Super minor style improvement...

2023-05-15 19:18 UTC, tynandebold approved these changes
Excellent!

2023-05-16 08:30 UTC, antonymilne requested changes
I'm pretty sure this is ok, but I've been reading sqlalchemy docs some more and just want to check one thing... So please hold off on merging just for now!

2023-05-16 09:37 UTC, antonymilne approved these changes
@rashidakanchwala I just did a bit of re-naming and put in a new TODO.

This is a great change, but let's look at making further improvements straight after v1 of collaborative experiment tracking is done because I think there's a bit more reorganisation to do.

2023-05-16 12:59 UTC, merged