Bugfix/kedro viz 1351 react18 dev mode bugs
kedro-org/kedro-viz pull request #1475
Opened 2023-08-03 10:28 UTC by vladimir-mck

## Description

Resolves [#1351](https://github.com/kedro-org/kedro-viz/issues/1351)

## Development notes

- The Router is always rendered since the FlowChartWrapper components is using router hooks
- Dropdown useEffect condition is updated to run only if there is a prop 
- `layout` is async to fix `TypeError: getJob(...).then is not a function` error
## QA notes

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

2023-08-03 14:52 UTC, ravi-kumar-pilla requested changes

2023-08-03 14:52 UTC, ravi-kumar-pilla commented on RELEASE.md
> +- Fix error error in dropdown component. (#1351)
can we have 1 release comment like **Fix dataset and global tool bar error with standalone React component** ?

2023-08-03 14:54 UTC, ravi-kumar-pilla commented
Hi @vladimir-mck ,

Nice work !! 

Can you please update the QA notes ? It will be helpful to quickly test the fix. Thank you !

2023-08-07 09:13 UTC, tynandebold approved these changes
Looks good! Thanks for your first PR. Here's to many more 💥

2023-08-07 09:13 UTC, tynandebold commented on RELEASE.md
> +- Fix dataset and global tool bar error with standalone React component (#1351)
```suggestion
- Fix dataset and global toolbar error with standalone React component (#1351)
```

2023-08-07 14:47 UTC, ravi-kumar-pilla commented
Hi @vladimir-mck, I am trying to test your PR locally

But, I am struggling to follow your QA notes. Do you think if we can use - https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557 to test quickly ?

When I am copying package.json from kedro viz and doing npm install in the new project created via CRA, I get lot of dependency errors. Is there a better way to test ? Thank you !

2023-08-07 17:05 UTC, ravi-kumar-pilla approved these changes
LGTM

2023-08-08 09:12 UTC, merged