Introduce --include-hooks option and deprecate --ignore-plugins in Kedro-Viz
kedro-org/kedro-viz pull request #1818
Opened 2024-03-26 16:39 UTC by ravi-kumar-pilla

## Description

Resolves #1808 

## Development notes

* Added `--include-hooks` option to all the viz cli commands (run, build, deploy)
* Added `--include-hooks` option to `%run_viz` Jupyter line magic
* Removed `--ignore-plugins` option from viz cli commands
* Updated pytests

## QA notes

* All tests should pass
* ` --include-hooks` should appear as an option with -h (eg., `kedro viz run -h`)

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [x] Added tests to cover my changes

2024-03-26 19:11 UTC, ravi-kumar-pilla commented
CircleCI Build fix - https://github.com/kedro-org/kedro-viz/pull/1819

2024-04-02 12:55 UTC, rashidakanchwala commented on README.md
> +  --save-file FILE          Save all API responses from the backend as JSON
since this is more user facing I was thinking maybe we stick to the old 
'Save Kedro-Viz data as JSON files in a specified directory'

2024-04-02 13:50 UTC, rashidakanchwala approved these changes
Looks great to me !! thanks @ravi-kumar-pilla

2024-04-03 10:56 UTC, SajidAlamQB approved these changes
LGTM, thank you @ravi-kumar-pilla!

2024-04-04 08:34 UTC, merelcht requested changes
The code itself looks good, but I just wanted to clarify if `--ignore-plugins` is meant to be deprecated, like it says in the release notes, or removed. And if it's removed will it be included in a breaking release?

2024-04-04 08:34 UTC, merelcht commented on RELEASE.md
> +- Introduce `--include-hooks` option and deprecate `--ignore-plugins` from cli commands. (#1818)
It says `--ignore-plugins` is deprecated, but from looking at the code it looks like it's removed?

2024-04-04 08:34 UTC, merelcht commented on RELEASE.md
> +- Introduce `--include-hooks` option and deprecate `--ignore-plugins` from cli commands. (#1818)
And is this going to be included in a breaking release?

2024-04-04 14:28 UTC, merelcht commented on RELEASE.md
> +- Introduce `--include-hooks` option and deprecate `--ignore-plugins` from cli commands. (#1818)
Deprecating and then removing would be the "right" process, but if no-one is using this flag I'm fine with removing straight away in a non-breaking release. Just make sure it's clear in the release notes 🙂

2024-04-04 14:29 UTC, merelcht approved these changes

2024-04-04 14:38 UTC, merged

2024-05-01 15:41 UTC, brau0300 commented
This (as expected it seems) was a breaking change for any project using hooks or plugins and was non-trivial to chase down.

It also makes it less convenient for especially new users on a project needing this flag to start kedro viz; would we be open to considering ways to pass this option (now required for certain projects) by default (e.g. via project configuration) and/or more succinctly?

2024-05-01 20:31 UTC, ravi-kumar-pilla commented
> This (as expected it seems) was a breaking change for any project using hooks or plugins and was non-trivial to chase down.
> 
> It also makes it less convenient for especially new users on a project needing this flag to start kedro viz; would we be open to considering ways to pass this option (now required for certain projects) by default (e.g. via project configuration) and/or more succinctly?

Hi @brau0300 , 

Thank you for the comment. Ideally Kedro-Viz does not need any hook to start. Users should be able to do `kedro viz run` without any issue. Having said that, could you please let us know the use case where you need a hook to be enabled for kedro viz to start ? 

At this moment, we do not have any discussions on making this available via configuration of some sort. But we would be happy to hear from you the pain points and the issue this would solve for Kedro-Viz. Thank you

2024-05-09 21:14 UTC, ravi-kumar-pilla commented
Hi @brau0300 , 

Thank you for the response. The idea behind ignoring hooks by default was to make Kedro-Viz faster and work towards https://github.com/kedro-org/kedro-viz/issues/1159 . I agree it is a breaking change, but the team decided to load Kedro-Viz with bare minimum of what it needs and users can opt in hooks if they want any additional functionality. 

For the issue of `dropping toposort`, this could have been avoided if Kedro-Viz refrained from using transitive dependencies. We have created a [ticket](https://github.com/kedro-org/kedro-viz/issues/1821) to make Kedro-Viz better and avoid any such instances in future. 

Thank you