Remove deploy to s3 circle ci step
kedro-org/kedro-viz pull request #706
Opened 2022-01-19 11:02 UTC by tynandebold

## Description

We're moving away from this deployment method, so let's remove this step.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

2022-01-19 11:05 UTC, limdauto approved these changes

2022-01-19 11:10 UTC, studioswong requested changes
This hasn't exactly been discussed and agreed amongst the team and should not be removed yet - this should only be deleted when we have reached a common consensus

2022-02-16 22:32 UTC, AntonyMilneQB approved these changes

2022-02-17 11:28 UTC, tynandebold commented
@studioswong following our discussion from Discord, it seems like we're all in agreement that we don't need the S3 step right now. I'll merge this in today if that's ok.

2022-02-17 11:32 UTC, studioswong approved these changes
yea let's remove this now that we have gitpod implemented.

2022-02-17 11:45 UTC, merged